#!/bin/bash
cabal new-build -w /usr/local/bin/ghc-8.0.2 --builddir dist-8.0.2 all
cabal new-build -w /usr/local/bin/ghc-8.2.2 --builddir dist-8.2.2 all
cabal new-build -w /usr/local/bin/ghc-8.4.2 --builddir dist-8.4.2 all
